[project]
name = "gooncli"
version = "1.0.2"
description = "Goon Project CLI Version"
authors = [
    { name="xyzvv9" }
]
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
goon = "gooncli.__main__:main"
